src/backend/apps/split_logs/urls.py
# -*- coding: utf-8 -*-
from apps.split_logs.views import APICourseDetails
from apps.split_logs.views import APICoursesList
from apps.split_logs.views import APIOrganisationsList
from apps.split_logs.views import CourseDetails
from apps.split_logs.views import IndexView
from apps.split_logs.views import OrganisationDetails
from django.urls import path
from django.urls import re_path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'split-logs'

urlpatterns = [
    path(
        "api/organisations/",
        APIOrganisationsList.as_view({"get": "list"}),
        name="split_logs",
    ),
    path(
        "api/courses/<int:organisation_id>/",
        APICoursesList.as_view({"get": "list"})
    ),
    path(
        "api/course/<int:pk>/",
        APICourseDetails.as_view({"get": "retrieve"})
    ),
    path(
        "api/course/<str:course_id>/",
        APICourseDetails.as_view({"get": "retrieve"})
    ),
    path(
        "organisation/<int:pk>/",
        OrganisationDetails.as_view(),
        name="organisation"
    ),
    path(
        "course/<int:pk>/<str:unit_id>/",
        CourseDetails.as_view(),
        name="unit"
    ),
    path(
        "ccourse/<int:pk>/",
        CourseDetails.as_view(),
        name="course"
    ),
    re_path(r"^.*", IndexView.as_view(), name="index")
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/backend/core/urls.py
# -*- coding: utf-8 -*-
"""swissmooc-extras URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path("app/", include("apps.split_logs.urls", namespace="split-logs")),
    path("", include("apps.home.urls", namespace="home")),
]

src/backend/apps/templates/includes/menu.html
{% load static %}

<nav
  class="navbar is-sticky-top navigation container"
  role="navigation"
  aria-label="main navigation"
>
  <div id="navbar-links" class="navbar-menu">
    <div class="navbar-brand">
      <a role="button" class="navbar-burger" data-target="navbar-links">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <a href="{% url 'split-logs:index' %}" class="navbar-item">
          Dashboard
        </a>
      </div>
    </div>
  </div>
</nav>