src/backend/apps/split_logs/urls.py
# -*- coding: utf-8 -*-
from apps.split_logs.views import APICourseDetails
from apps.split_logs.views import APICoursesList
from apps.split_logs.views import APIOrganisationsList
from apps.split_logs.views import CourseDetails
from apps.split_logs.views import IndexView
from apps.split_logs.views import OrganisationDetails
from django.urls import path
from django.urls import re_path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'split-logs'

urlpatterns = [
    path(
        "api/organisations/",
        APIOrganisationsList.as_view({"get": "list"}),
        name="split_logs",
    ),
    path(
        "api/courses/<int:organisation_id>/",
        APICoursesList.as_view({"get": "list"})
    ),
    path(
        "api/course/<int:pk>/",
        APICourseDetails.as_view({"get": "retrieve"})
    ),
    path(
        "api/course/<str:course_id>/",
        APICourseDetails.as_view({"get": "retrieve"})
    ),
    path(
        "organisation/<int:pk>/",
        OrganisationDetails.as_view(),
        name="organisation"
    ),
    path(
        "course/<int:pk>/<str:unit_id>/",
        CourseDetails.as_view(),
        name="unit"
    ),
    path(
        "ccourse/<int:pk>/",
        CourseDetails.as_view(),
        name="course"
    ),
    re_path(r"^.*", IndexView.as_view(), name="index")
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/backend/core/urls.py
# -*- coding: utf-8 -*-
"""swissmooc-extras URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path("app/", include("apps.split_logs.urls", namespace="split-logs")),
    path("", include("apps.home.urls", namespace="home")),
]

src/backend/apps/split_logs/models.py
# -*- coding: utf-8 -*-
import datetime

from django.conf import settings
from django.db import models


DB_TYPE_MYSQL = 'mysql'
DB_TYPE_MONGO = 'mongo'
DB_TYPE_CHOICES = (
    (DB_TYPE_MYSQL, DB_TYPE_MYSQL),
    (DB_TYPE_MONGO, DB_TYPE_MONGO),
)


class DirOriginal(models.Model):
    name = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class FileOriginal(models.Model):
    name = models.CharField(max_length=255)
    dir_original = models.ForeignKey(DirOriginal, on_delete=models.CASCADE)
    lines_total = models.PositiveIntegerField(default=0)
    lines_error = models.PositiveIntegerField(default=0)

    @property
    def fullname(self):
        return "{}/{}".format(self.dir_original, self.name)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fullname

    class Meta:
        unique_together = (("name", "dir_original"),)


class FileOriginalDocker(models.Model):
    name = models.CharField(max_length=255)
    dir_original = models.ForeignKey(DirOriginal, on_delete=models.CASCADE)
    lines_total = models.PositiveIntegerField(default=0)
    lines_error = models.PositiveIntegerField(default=0)

    @property
    def fullname(self):
        return "{}/{}".format(self.dir_original, self.name)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fullname

    class Meta:
        unique_together = (("name", "dir_original"),)


class PublicKey(models.Model):
    name = models.CharField(max_length=128)
    recipient = models.CharField(max_length=128)
    value = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Organisation(models.Model):
    name = models.CharField(max_length=255, unique=True)
    aliases = models.CharField(max_length=1024)
    public_key = models.ForeignKey(
        PublicKey,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def bucket_name(self):
        return f"{settings.AWS_STORAGE_BUCKET_NAME_ANALYTICS}-{self.name.lower()}"

    def __str__(self):
        return self.name


class Course(models.Model):
    course_id = models.CharField(max_length=255)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    structure = models.JSONField(default=dict, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def folder(self):
        return self.course_id.replace('+', '-').replace('course-v1:', '')

    def __str__(self):
        return self.course_id

    class Meta:
        unique_together = (('course_id', 'organisation'),)


class CourseDumpTable(models.Model):
    db_type = models.CharField(
        choices=DB_TYPE_CHOICES,
        max_length=128,
        default=DB_TYPE_MYSQL
    )
    name = models.CharField(max_length=255)
    db_name = models.CharField(max_length=255)
    primary_key = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}/{}.{}'.format(self.db_type, self.db_name, self.name)


class CourseDump(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    table = models.ForeignKey(CourseDumpTable, on_delete=models.CASCADE)
    date = models.DateField()
    is_encypted = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.course.course_id

    def dump_folder_name(self):
        return '{path}/{org_name_lower}-{date}'.format(
            path=settings.DUMP_DB_PATH,
            org_name_lower=self.course.organisation.name.lower(),
            date=datetime.datetime.now().strftime('%Y-%m-%d'),
        )

    def dump_file_name(self):
        if self.table.db_type == DB_TYPE_MYSQL:
            suffix = 'prod-analytics.sql'
        elif self.table.db_type == DB_TYPE_MONGO:
            suffix = 'prod.mongo'
        else:
            raise Exception("Unsupported db_type table")

        # epflx-2019-04-21/EPFLx-Algebre2X-1T2017-auth_user-prod-analytics.sql.gpg
        return "{folder_name}/{course_folder}-{table_name}-{suffix}".format(
            folder_name=self.dump_folder_name(),
            course_folder=self.course.folder,
            table_name=self.table.name,
            suffix=suffix,
        )

    def encrypred_file_name(self):
        return '{}.gpg'.format(self.dump_file_name())

    class Meta:
        unique_together = (('course', 'table', 'date'),)

src/backend/apps/split_logs/views.py
# -*- coding: utf-8 -*-
import logging

from apps.split_logs.models import Course
from apps.split_logs.models import Organisation
from apps.split_logs.serializers import CourseListSerializer
from apps.split_logs.serializers import CourseSerializer
from apps.split_logs.serializers import OrganisationSerializer
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic import ListView
from rest_framework.response import Response
from rest_framework.viewsets import ReadOnlyModelViewSet

logger = logging.getLogger(__name__)


class IndexView(ListView):
    template_name = 'split_logs/index.html'
    context_object_name = 'organisation_list'

    def get_queryset(self):
        return Organisation.objects.all()


class OrganisationDetails(DetailView):
    model = Organisation
    template_name = 'split_logs/organisation.html'


class CourseDetails(DetailView):
    model = Course
    template_name = 'split_logs/course.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'unit_id' in self.kwargs:
            context['unit_id'] = self.kwargs['unit_id']
            context['tasks'] = [1, 2, 3]
        else:
            context['unit_id'] = None
            context['tasks'] = None
        return context


class APIOrganisationsList(ReadOnlyModelViewSet):
    queryset = Organisation.objects.filter(active=True)
    serializer_class = OrganisationSerializer
    # permission_classes = [permissions.IsAuthenticated]


class APICoursesList(ReadOnlyModelViewSet):
    lookup_organisation_id_kwarg = "organisation_id"
    serializer_class = CourseListSerializer
    # permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        organisation_id = self.kwargs.get(self.lookup_organisation_id_kwarg)
        courses = Course.objects.filter(active=True, organisation_id=organisation_id)
        return courses


class APICourseDetails(ReadOnlyModelViewSet):
    serializer_class = CourseSerializer
    # permission_classes = [permissions.IsAuthenticated]

    def retrieve(self, request, pk=None, course_id=None):
        queryset = Course.objects.all()
        if pk:
            course = get_object_or_404(queryset, pk=pk)
        else:
            course = get_object_or_404(queryset, course_id=course_id)
        serializer = CourseSerializer(course)
        return Response(serializer.data)

src/backend/apps/templates/split_logs/course.html
{% extends "layouts/base.html" %}
{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="columns">
  <div class="column is-8 is-offset-2">
    <div id="split-logs-app">
      {% for chapter in course.structure.children %}
      <div class="card mb-3">
        <header class="card-header">
          <p class="card-header-title">
            Chapter: {{ chapter.name }}
          </p>
        </header>
        <div class="card-content">
          <div class="content">
            {% for sequential in chapter.children %}
            <div class="card mb-3">
              <header class="card-header">
                <p class="card-header-title">
                  Sequential: {{ sequential.name }}
                </p>
              </header>
              <div class="card-content">
                <div class="content">
                  {% for vertical in sequential.children %}
                  <div class="card mb-3">
                    <header class="card-header">
                      <p class="card-header-title">
                        Vertical: {{ vertical.name }}
                      </p>
                    </header>
                    <div class="card-content">
                      <div class="content">
                        {% for unit in vertical.children %}
                        <div class="card mb-3">
                          <header class="card-header">
                            <p class="card-header-title">
                              Unit: {{ unit.name }}
                            </p>
                          </header>
                          <div classs="card-content">
                            <div class="content p-2 pl-4">
                              {{unit.type}}:
                              <a href="{% url 'split-logs:unit' course.id unit.id %}">
                                {{ unit.name }}
                              </a>
                              {% if unit.id == unit_id %}
                              {{unit_id}}
                              {% endif %}
                            </div>
                          </div>
                        </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

src/backend/apps/templates/split_logs/index.html
{% extends "layouts/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="columns">
  <div class="column is-8 is-offset-2">
    <div id="split-logs-app">
      {% for org in organisation_list %}
      <a href="{% url 'split-logs:organisation' org.id %}">
        {{org}}
      </a>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

src/backend/apps/templates/split_logs/organisation.html
{% extends "layouts/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div class="columns">
  <div class="column is-8 is-offset-2">
    <div id="split-logs-app">
      {% for course in organisation.course_set.all %}
      <div>
        <a href="{% url 'split-logs:course' course.id %}">
          {{ course.course_id }}
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}